services:
  sms:
    image: sms-external-service:v1.1
    # network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VONAGE_FROM: from JDB
      VONAGE_API_KEY: 8f7dee78
      VONAGE_API_SECRET: V2uruA9F1Q9XjkH0
      SMS_SIGNATURE_SECRET: nUwskffw1lPwVS
      SMS_CALLBACK_URL: localhost/webhooks/dlr
      DB_USER: JDBINHOUSEUAT
      DB_PASSWORD: "InhUat#35"
      DB_CONNECT_STRING: 172.21.21.35:1521/JDBDEVDB.JDB.LOCAL
    ports:
      - 3000:3000
    # env_file:
    #   - .env
# docker build --platform=linux/amd64 -t sms-external-service:v1.0 .
#  docker tag sms-external-service:v1.0 172.21.25.120:5000/inhourse-uat/sms-external-service:v1.0
#  docker push 172.21.25.120:5000/inhourse-uat/sms-external-service:v1.0

